_target_: diffusion_policy.workspace.train_diffusion_transformer_hybrid_workspace.TrainDiffusionTransformerHybridWorkspace
checkpoint:
  - save_last_ckpt: true
    save_last_snapshot: false
    topk:
      format_str: epoch={epoch:04d}-val_loss={val_loss:.4f}-val_ddim_mse={val_ddim_mse:.4f}.ckpt
      k: 5
      mode: min
      monitor_key: val_loss_0
  - save_last_ckpt: true
    save_last_snapshot: false
    topk:
      format_str: epoch={epoch:04d}-val_loss={val_loss:.4f}-val_ddim_mse={val_ddim_mse:.4f}.ckpt
      k: 5
      mode: min
      monitor_key: val_ddim_mse_0
dataloader:
  batch_size: 64
  num_workers: 8
  shuffle: true
  pin_memory: true
  persistent_workers: false
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999
keypoint_visible_rate: 1.0
task_name: planar_pushing
logging:
  project: dit_planar_pushing
  resume: True
  mode: online
  name: CL_16
  tags: ["${name}", "${task_name}"]
  id: null
  group: null
multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
horizon: 24
n_obs_steps: 16
n_action_steps: 8
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: false
obs_as_cond: true
name: train_diffusion_transformer_hybrid
optimizer:
  transformer_weight_decay: 1.0e-3
  obs_encoder_weight_decay: 1.0e-6
  learning_rate: 1.0e-4
  betas: [0.9, 0.95]
shape_meta:
  action:
    shape:
    - 2
  obs:
    agent_pos:
      shape:
      - 3
      type: low_dim
    overhead_camera:
      shape:
      - 3
      - 128
      - 128
      type: rgb
    wrist_camera:
      shape:
      - 3
      - 128
      - 128
      type: rgb
policy:
  _target_: diffusion_policy.policy.diffusion_transformer_hybrid_image_policy.DiffusionTransformerHybridImagePolicy

  shape_meta: ${shape_meta}
  
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    variance_type: fixed_small # Yilun's paper uses fixed_small_log instead, but easy to cause Nan
    clip_sample: True # required when predict_epsilon=False
    prediction_type: epsilon # or sample

  horizon: ${horizon}
  n_action_steps: ${n_action_steps}
  n_obs_steps: ${n_obs_steps}
  num_inference_steps: 100

  crop_shape: [76, 76]
  obs_encoder_group_norm: true
  eval_fixed_crop: true

  n_layer: 8
  n_cond_layers: 0  # >0: use transformer encoder for cond, otherwise use MLP
  n_head: 4
  n_emb: 256
  p_drop_emb: 0.0
  p_drop_attn: 0.3
  causal_attn: true
  time_as_cond: true # if false, use BERT like encoder only arch, time as input
  obs_as_cond: ${obs_as_cond}

  # # scheduler.step params
  # predict_epsilon: true
task:
  dataset:
    _target_: diffusion_policy.dataset.planar_pushing_dataset.PlanarPushingDataset
    shape_meta: ${shape_meta}
    horizon: ${horizon}
    n_obs_steps: ${n_obs_steps}
    pad_after: 7
    pad_before: 15
    seed: 42
    zarr_configs:
    - path: data/planar_pushing_cotrain/sim_sim_tee_data_carbon_large.zarr
      max_train_episodes: 160
      sampling_weight: null
      val_ratio: 0.0625 # 10 / 160 trajectories
  name: scene_image
  shape_meta: ${shape_meta} # not used?
training:
  device: "cuda:0"
  seed: 42
  debug: false
  resume: true
  # optimization
  lr_scheduler: cosine
  # Transformer needs LR warmup
  lr_warmup_steps: 500
  num_epochs: 300
  gradient_accumulate_every: 1
  # EMA destroys performance when used with BatchNorm
  # replace BatchNorm with GroupNorm.
  use_ema: true
  # training loop control
  # in epochs
  rollout_every: 5
  checkpoint_every: 5
  val_every: 1
  sample_every: 5
  # steps per epoch
  max_train_steps: null
  max_val_steps: null
  # misc
  log_val_mse: true
  tqdm_interval_sec: 30.0
  eval_mse_DDIM: true
  eval_mse_DDPM: true
val_dataloader:
  batch_size: 64
  num_workers: 8
  shuffle: False
  pin_memory: True
  persistent_workers: False

# hydra:
#   job:
#     override_dirname: ${name}
#   run:
#     dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
#   sweep:
#     dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
#     subdir: ${hydra.job.num}
